ord(c) causes script to malfunction
Hi, I was trying to execute truecrypt commands with volatility, and I got the following error : "c for c in passphrase if ord(c) >= 0x20 and ord(c) <= 0x7F 
TypeError: ord() expected string of length 1, but int found". I found this answer online to fix it : https://stackoverflow.com/a/19897878. Basically I just removed the "ord()" and it works now !